disabled_rules: # rule identifiers to exclude from running
  - opening_brace
  - non_optional_string_data_conversion

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift
  - Carthage
  - .build

type_body_length:
  - 300 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 800

line_length:
  warning: 175
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 3
   - 4

opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - duplicate_imports
  - empty_string
  - force_unwrapping
  - implicit_return
  - let_var_whitespace
  - nslocalizedstring_key
  - private_action
  - private_outlet
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - custom_rules
  - expiring_todo
  - implicitly_unwrapped_optional
  - operator_usage_whitespace

conditional_returns_on_newline:
  severity: error
  if_only: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true
  
discouraged_direct_init:
  severity: error
  types:
    - Bundle
    - UIDevice
    - UIScreen
    - UIApplication

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

function_parameter_count:
  warning: 5
  error: 5

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 64
  excluded:
    - id

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

switch_case_on_newline:
  severity: error

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 1000
  excluded:
    - "ID"
    - "Id"
    - "ios_boilerplateTests"
    - "ios_boilerplateUITests"

unneeded_break_in_switch:
  severity: error

expiring_todo:
  date_format: "dd.MM.yyyy"
  date_separator: "."

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
    - identifier
    message: "Don't commit `print(…)`, `debugPrint(…)`, or `dump(…)` as they write to standard out in release. Either log to a dedicated logging system or silence this warning in debug-only scenarios explicitly using `// swiftlint:disable:next no_direct_standard_out_logs`"
    severity: warning
  no_file_literal:
    name: "#file is disallowed"
    regex: "(\\b#file\\b)"
    match_kinds:
    - identifier
    message: "Instead of #file, use #fileID"
  no_filepath_literal:
    name: "#filePath is disallowed"
    regex: "(\\b#filePath\\b)"
    match_kinds:
    - identifier
    message: "Instead of #filePath, use #fileID."